# Generated by Django 4.1 on 2022-08-28 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=100, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('avatar', models.CharField(max_length=255, null=True)),
                ('is_active', models.BooleanField(verbose_name=False)),
                ('status', models.IntegerField(default=0, max_length=1)),
            ],
        ),
    ]
